version: "3.8"

services:
  server:
    user: root
    image: "nginx:stable-alpine"
    ports:
    - "8000:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./backend:/var/www/html
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - frontend

  php:
    build:
      context: ./docker-files
      dockerfile: php.dockerfile
    volumes:
    - ./backend:/var/www/html:delegated

  mysql:
    build:
      context: docker-files
      dockerfile: mysql.dockerfile
    env_file:
      - ./env/mysql.env

  composer:
    user: root
    build:
      context: ./docker-files
      dockerfile: composer.dockerfile
    volumes:
    - ./backend:/var/www/html


  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
    - ./backend:/var/www/html

  artisan:
    build:
      context: ./docker-files
      dockerfile: php.dockerfile
    volumes:
    - ./backend:/var/www/html
    entrypoint: ["php","/var/www/html/artisan"]

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - default
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  frontend:
    build:
      context: frontend
      dockerfile: frontend.dockerfile
    ports:
    - "4200:80"

